services:
  census-mcp-db:
    image: postgres:16
    environment:
      POSTGRES_DB: mcp_db
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: mcp_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./mcp-db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcp_user -d mcp_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  census-mcp-db-test:
    image: postgres:16
    environment:
      POSTGRES_DB: mcp_db_test
      POSTGRES_USER: mcp_user_test
      POSTGRES_PASSWORD: mcp_pass_test
    volumes:
      - ./mcp-db/init:/docker-entrypoint-initdb.d  # Same basic setup
      # No persistent volume - fresh on each start
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcp_user_test -d mcp_db_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: [test]

  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    container_name: mcp-server
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: census-mcp-db
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: mcp_pass
      NODE_ENV: production
    depends_on:
      census-mcp-db:
        condition: service_healthy
    volumes:
      - ./shared:/app/shared:ro
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    name: census-mcp-network