name: MCP Database - Lint

on:
  push:
    branches: ['main']
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  build:
    name: Code Quality Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

       # Build MCP DB
      - name: Install MCP Database dependencies
        working-directory: ./mcp-db
        run: npm ci

      - name: Run ESLint in MCP Database
        working-directory: ./mcp-db
        run: npm run lint
   
 